site_name: Antony Messerli
docs_dir: resume
google_analytics: ['UA-68807-9', 'antony.mes.ser.li']
pages:
- Home: 'index.md'
- Experience:
    - 'Rackspace': 'rackspace.md'
    - 'Titan': 'titan.md'
- About Me:
    - 'Skills': 'skills.md'
    - 'Projects': 'projects.md'
    - 'Contact Me': 'contact.md'
theme: cyborg
