site_name: Antony Messerli
site_description: The resume of Antony Messerli
site_author: Antony Messerli
site_url: https://antony.mes.ser.li
copyright: © 2016 <a href="https://twitter.com/@ntonym">Antony Messerli</a>
docs_dir: resume
google_analytics: ['UA-68807-9', 'antony.mes.ser.li']
pages:
- Home: 'index.md'
- Experience:
    - 'Rackspace': 'rackspace.md'
    - 'Titan': 'titan.md'
- About Me:
    - 'Skills': 'skills.md'
    - 'Projects': 'projects.md'
    - 'Contact Me': 'contact.md'
theme: cyborg
